version: '3.9'

services:
  server:
    container_name: e_book_backend
    image: e_book_backend:0.0.1
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      DEV_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    networks:
      - shared-network
    volumes:
      - .:/app/backend
      - /app/backend/node_modules
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: "postgres"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - shared-network
    volumes:
      - nps_data:/var/lib/postgresql/data
  react-app:
    build: ../Ebooking-front-end/e-booking
    volumes:
      - /app/node_modules
      - ../Ebooking-front-end/e-booking:/app
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  nps_data:
networks:
  shared-network: